### ISSUE TITLE
Navigation Tweaks: Re-work for mobile

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/bezos-frontend#11]
## Description

The current navigation layout was more or less copied over from the dApp.
The actual mobile design looks like this:

<img width="695" alt="mobile" src="https://user-images.githubusercontent.com/95881624/203724874-47b8f9d5-bdb4-4780-b809-c4bca572012b.png">

=> link to [figma](https://www.figma.com/file/2elL0wanKxc3I9n6zO5vjC/Project-Bezos?node-id=302%3A18622&t=nPZEmvJIxteUx0zJ-0)

## TODOs

- [x] move the offcanvas menu from left to right
- [x] add marketplace logo
- [x] move hamburger menu icon from left to right
- [x] move dark/lightmode toggle button to offcanvas menu (missing in design!)
- [x] move connect/disconnect button to offcanvas menu (missing in design)
- [x] change icon for "Edit profile" button on mobile (see screenshot below)

<img width="341" alt="edit" src="https://user-images.githubusercontent.com/95881624/203725675-6870ff73-7ba1-44b1-aae6-32c40f22cdbd.png">
