### ISSUE TITLE
API: List of open questions

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/bezos-frontend#12]
## Missing data

- [x] GET user => listings.project => Please add more **unique data for every project** a user has listed. We need to fetch more data per project to render the UI (name, vintage, category, key, link to project).
- [x] GET user => listings.project => **category** is missing but defined in specs (Example [link](https://marketplace-api-najada.vercel.app/api/users/0xD1a3699f2098ac92C2f4914979FCb22aba86D259?type=wallet))
- [x] GET user => listings.project => **timestamp** for sorting
- [x] GET user activities => project data is `null` on activityType "UpdatedPrice" and "DeletedListing"
- [x] GET categories => empty result (Example [link](https://marketplace-api-najada.vercel.app/api/categories)) => not working when on Mumbai, see [ticket](https://github.com/Atmosfearful/bezos-frontend/issues/15)
- [x] GET countries => response doe snot contain same country as in for GET projects => not working when on Mumbai, see [ticket](https://github.com/Atmosfearful/bezos-frontend/issues/15)
- [x] GET countries => actual response (`id: <countryName>`) and the docs (`name: <countryName>`) are not aligned ([Api response](https://marketplace-api-najada.vercel.app/api/countries), See link to [Docs](https://marketplace-api-najada.vercel.app/documentation/static/index.html)) => not working when on Mumbai, see [ticket](https://github.com/Atmosfearful/bezos-frontend/issues/15)
- [x] GET project/ID => does each projects have the listings attached? => see [design](https://www.figma.com/file/2elL0wanKxc3I9n6zO5vjC/Project-Bezos?node-id=31%3A11&t=uzh4Kd1r9zvBL63D-0)
- [x] GET project/ID listing => attach seller data
- [x] GET project/ID category, GET projects, GET user listings project => category is not aligned
- [x] GET vintages ?

## Deleting Listing
- [x] API is not updating data with the removed listings
- [x] API does not update user's activity

## API docs
=> https://marketplace-api-najada.vercel.app/documentation/static/index.html

## Related Ticket
=> [Categories: Map IDs to Strings](https://github.com/Atmosfearful/bezos-frontend/issues/8)

##
- [ ] listings.leftToSell and totalToSell => different amount than in metamask
