### ISSUE TITLE
[environments] Switch from Mumbai to Mainnet To-do's

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/bezos-frontend#15]
## Description

The marketplace API is still querying the data from the polygon testnet mumbai.

Therefore some API endpoint do not work:
- GET countries (without pool projects)
- GET categories(without pool projects)
- GET vintages
- GET projects (contains only projects which have been created on Mumbai and not all possible projects)
- GET user data with correct asset data

## TODO
When switching over to mainnet make sure to change this before:
- [x] Change mainnet marketplace address in lib/constants to the new polygon address
- [x] Change subgraph address in lib/constants (may not be necessary)
- [x] Remove fake USDC token address "0x284A5F4d90a49F7eb21C055eA3C824603314B1E7" and use normal USDC contract
- [x] Change transactons links from `https://mumbai.polygonscan.com/tx/...` to mainnet
- [x] Change USDC input (singleUnitPrice) parseUnits value from 18 to 6
- [x] Change all places with `urls.polygonTestnetRpc ` to `urls.polygonMainnetRpc`
