### ISSUE TITLE
[Create profile|: Align with backend validations

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/bezos-frontend#160]
## Description

Description was optional, now the backend rejects if this value is not over 2 characters.

![Bildschirm­foto 2023-02-09 um 12 20 05](https://user-images.githubusercontent.com/95881624/217802500-c91c33b3-40e7-4b6c-a925-b90800fa1139.png)

See screenshots in this pull requests https://github.com/Atmosfearful/bezos-frontend/pull/161

## TODO
- [ ] Get all validation rules from backend dev (see beloq)
- [ ] Discuss which ones should be aligned on the Client
- [ ] Implement the same validation on the input fields (to disable submit)
