### ISSUE TITLE
[styles ui] Better Project Select DropDown

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/bezos-frontend#17]
## Description

The current Tippy Dropdown for the project Selection on "Create a new Listing" can be improved.

## Current State
<img width="617" alt="Bildschirm­foto 2023-01-03 um 10 22 00" src="https://user-images.githubusercontent.com/95881624/210400381-7c281a8e-1997-415d-8012-43351d469981.png">

## TODO
- [ ] give dropdown same width as current selection header
- [ ] In general: make it more look like a proper dropdown
- [ ] if in doubt talk to design (dropdown design is missing in Figma)
