### ISSUE TITLE
[projects] Browse projects page

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/bezos-frontend#18]
## Description

The project index page with a complex search/filter/sort UI

<img width="1081" alt="projects" src="https://user-images.githubusercontent.com/95881624/213512201-4ebe376b-a3ad-4c88-8761-355669ee9a7d.png">

**Frontend:**
https://carbonmark.vercel.app/projects

**Design:**
https://www.figma.com/file/2elL0wanKxc3I9n6zO5vjC/Project-Bezos?node-id=302%3A18622&t=GnOG0bDIwIfYjW0U-0

**API:**
https://marketplace-api-najada.vercel.app/api/projects
https://marketplace-api-najada.vercel.app/documentation/static/index.html

## TODO
- [x] get all projects data from API (projects from sellers and from carbon pools)
- [x] render index page with a responsive list of projects (see design)
- [ ] integrate complex filter options (see design)
- [ ] query API when user filters results
