### ISSUE TITLE
[project] Build project single page

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/bezos-frontend#19]
## Description

**Frontend:**
https://bezos-frontend.vercel.app/marketplace/projects/GS-500-2020

**Design:**
https://www.figma.com/file/2elL0wanKxc3I9n6zO5vjC/Project-Bezos?node-id=36%3A1980&t=GnOG0bDIwIfYjW0U-0

**API:**
https://marketplace-api-najada.vercel.app/api/projects/GS-500-2020
https://marketplace-api-najada.vercel.app/documentation/static/index.html

## TODO
- [x] get all project data from API
- [x] render single project page with active listings of different sellers
- [ ] render single project listings from pool #128 
- [x] [icebox] show stats and activity of this project #93 
- [ ] Map: render nice map #116 
- [ ] show description #129
