### ISSUE TITLE
[portfolio] Build Portfolio page

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/bezos-frontend#20]
## Description

**Frontend**
https://bezos-frontend.vercel.app/marketplace/portfolio
=> only visible/accessible if connected to wallet

**Design**
https://www.figma.com/file/2elL0wanKxc3I9n6zO5vjC/Project-Bezos?node-id=171%3A12020&t=GnOG0bDIwIfYjW0U-0

**API:**
https://marketplace-api-najada.vercel.app/api/users/0xD1a3699f2098ac92C2f4914979FCb22aba86D259?type=wallet

## TODO
- [x] render all projects/assets of the connected user
- [ ] integrate option to sell project (same "create a listing" modal within this view ??)
- [x] integrate option to retire the asset
- [ ] render balances of the user
- [x] render activity and stats of the user
- [ ] Decisions: Show only USDC balance (no c3, no tc02 for go-live)

## Questions?

- [x] when selling an asset => render the same "Create a Listing" Modal here on this page? => yes
- [x] Retire => simply deep link to klima-app? How exactly?
- [x] why rendering all possible balances when marketplace is only working with USDC only?

## Screenshots
<img width="610" alt="Bildschirm­foto 2023-02-01 um 10 09 29" src="https://user-images.githubusercontent.com/95881624/215999861-5aa39c60-bc1b-4fb6-bcd7-bb594b6f159a.png">
