### ISSUE TITLE
[assets] Read project data from TCO2 tokens 

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/bezos-frontend#231]
## Description

This is a follow-up on this PR https://github.com/Atmosfearful/bezos-frontend/pull/227

## TODO
- [x] iterate over all assets of a user
- [x] if a token is of type "TCO2" and the API does not return data for the Single porject endpoint => fall back to contract methods
- [x] add Toucan ABI (see below)
- [x] figure out which methods to call to get all relevant data the UI needs (see blow)

ABI can be found here
https://polygonscan.com/address/0x098bcd2dd9ed7897f5a303079012eeccbbb87aa0#code

The method you need is `getAttributes()` which returns 2 arrays, documented here:
https://docs.toucan.earth/toucan/dev-resources/smart-contracts/tco2#getattributes

Beware that many of these may be undefined or empty strings (not sure what ethers gives us) for example:

![image](https://user-images.githubusercontent.com/88635679/220221520-a63372aa-6fec-489b-8f54-b852e05506df.png)
