### ISSUE TITLE
[portfolio] Show all balances of the user 

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/bezos-frontend#232]
## Description

This is a follow-up on this PR https://github.com/Atmosfearful/bezos-frontend/pull/227

## TODO
- [ ] iterate over all assets the user is having (data comes from API)
- [ ] sum up all C3 tokens
- [ ] sum up all TCO2 tokens
- [ ] render the balances on the portfolio Balances card

<img width="489" alt="Bildschirm­foto 2023-02-08 um 13 40 58" src="https://user-images.githubusercontent.com/95881624/217534057-acdecb2e-34eb-4f23-bcff-463b5e854be4.png">
