### ISSUE TITLE
[environments] Move Marketplace to carbonmark.com

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/bezos-frontend#32]
## Description

Goal is that marketplace becomes its own
- repo (in klimadao repo?)
- domain on vercel
- maybe create own design schema (css variables, component design? etc)

This needs some developer work

## OPEN TODOs

- [x] add google script to document KlimaDAO/bezos-frontend#109
- [x] Replace scripts and URLs to new carbonmark domain in `carbonmark/components/shared/PageHead`
- [x] Fix: calculate price in PurchaseForm results in invinite loop
- [x] Rename all "marketplace" strings to "carbonmark"
- [x] Replace sign message with "carbonmark" text:   `Sign to authenticate ownership and edit your Klima Marketplace Profile 💚\n\nSignature nonce: ${nonce}`; => ALIGN WITH API DEV FOR THIS CHANGE! KlimaDAO/bezos-frontend#103 
- [x] KlimaDAO/bezos-frontend#157
- [x] make Footer work (not a shared component?) => PR https://github.com/Atmosfearful/bezos-frontend/pull/85
- [x] KlimaDAO/klimadao#1011
- [ ] ~get Resources integrated~=> new ticket https://github.com/Atmosfearful/bezos-frontend/issues/43
