### ISSUE TITLE
[resources] Duplicate Resources section from site to carbonmark

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/bezos-frontend#43]
# Description
In order to capture SEO and backlinks on day 1 of the launch of carbonmark.com, we decided we need a blog.
The easiest way to do this is to reuse everything we have built already: [klimadao.finance/resources](https://klimadao.finance/resources)

- Creatives will be able to write a blogpost in the klimadao cms just like before
- They can decide which domain it should be posted on. `Klimadao.finance/resources` or `carbonmark.com/resources`
- Klima posts NEVER appear on carbonmark, and carbonmark posts NEVER appear on klimadao. This is because duplicate content is disliked by search engines.
- The content team will write some blog posts to appear on carbonmark on day one. Just a few posts, maybe 1 or two categories

# Considerations

All of the /resources stuff exists in the `site` package. But `carbonmark` now has it's own package. This means we should at some point migrate shared things into `lib`. HOWEVER I fear that design and requirements may diverge so I would like us to wait until we have more insight into design. This is why we will **copy-paste first, and abstract later after launch.**

If you do need to abstract something to lib first, please let me know. It will need to happen on klimadao main repo and be rebased into this secret repo.

# TODO
* [x] Add carbonmark and vercel preview link domains to the whitelisted domains in sanity dashboard
 - atmos did this already
* [ ] Get list of launch-day categories from the content team
  - The "Medium" section is hidden because we do not have podcasts
![image](https://user-images.githubusercontent.com/88635679/213333191-fda32837-b8ba-46a2-a687-28786092274a.png)
* [ ] Add a row to the blog post schema that allows the content team to choose `domain: "klimadao" | "carbonmark"` using a dropdown.
 - only ever one domain at a time, never both
 - do this as a PR in this repo, when it is merged I will need to deploy it to sanity.
* [ ] Copy paste all /resources components and queries from `site` to `carbonmark`
  - Update query so it only pulls carbonmark posts

After launch: migrate the copy pasted components to shared components exported from /lib
