### ISSUE TITLE
[projects] Render Pool Projects

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/bezos-frontend#59]
## Description

As soon as this ticket is done https://github.com/Atmosfearful/bezos-frontend/issues/31
=> the following API endpoints will contain not only carbonmark but also projects from the carbon pools
- https://marketplace-api-najada.vercel.app/api/projects
- https://marketplace-api-najada.vercel.app/api/projects/POOL-PROJECT-ID

If a project is coming from a carbon pool, a lot of data is missing:
- category, country, activities, listings ...

This PR here prepared the types and UI to not crash when data is missing:
https://github.com/Atmosfearful/bezos-frontend/pull/58

Additionally, to distinguish between a pool project and a carbonmark project a boolean is added to the project data: `isPoolProject`

## TODO
- [x] add a default image when `category` is missing
- [x] fallback to a new category like "no category" or alike when category is missing?
- [x] render map
- [x] render description
- [x] render a custom listing on project single view (see screenshot below) 
- [x] Get correct "recycling" icon for the pool projects (missing here https://mui.com/material-ui/material-icons/, asked ProfessorA for this)
- [x] if pool project => render these stats https://github.com/Atmosfearful/bezos-frontend/issues/93

![delete_me](https://user-images.githubusercontent.com/95881624/214334970-c005a670-3ca3-493d-abf1-d6a2c4ec45fa.png)
