### ISSUE TITLE
[header ui] Disable languages

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/bezos-frontend#82]
## Description

For the go-live there won't be the option to change the language.

Still, Nextjs is detecting the browser´s language and switches accordingly.
This should be disabled.

## TODO
- [x] check carbonmark next.config.js and remove all possible locales
- [x] set "languageDetection" to false
- [x] check the lingui config for carbonmark and disable all languages (if needed)
- [x] ensure that the LanguageToggle is removed from all pages (and check that the UI is still looking good without it)
