### ISSUE TITLE
Activities: map activity types to components 

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/bezos-frontend#9]
## Description

Every marketplace user can have a list of activities.
These activities should be shown as a readable list.

### Current status

Activity type is always rendered as "some tonnes at some price" (Type: "CreatedListing")
which is not correct when an activity was e.g. "Sold" or "UpdatedQantity"

This is how the list should be rendered (screenshot from Figma Designs):
<img width="305" alt="desgin" src="https://user-images.githubusercontent.com/95881624/203545534-55710dc1-0d88-413b-ab4c-785e107527ff.png">

This is how the activity data looks like:

```TS
type Activity = {
  id: number;
  activityType: string; // CreatedListing, ...
  amount: number;
  previousAmount: number;
  price: number;
  previousPrice: number;
  timeStamp: number;
  batchPrices: [];
  singleUnitPrice: number;
  project: {
    key: string; // e.g. "GS-500"
  };
  seller: {
    id: string; // address
  };
  buyer: {
    id: string; // address
  };
};
```

## TODOS

- [x] get the project name according to `activity.project.key` (why is the name not already in the data?)
- [x] format prices correctly (which units is this?)
- [x] format amounts correctly (which unit is this?)
- [x] map activityType to translation string (e.g. "CreatedListing" => "created a listing")
- [x] map activity result to "bought from", "sold to", "updated price" .... (if buyer exist and previousAmount is XY => get correct translation string and pass numbers etc)

## Links

See here pages with activities (current status: activity type is always rendered as "some tonnes at some price" )
- https://carbonmark.vercel.app/users/LadyTestAccount2
- https://carbonmark.vercel.app/users/pixellll
- https://carbonmark.vercel.app/projects/VCS-487-2013
- https://carbonmark.vercel.app/projects/GS-500-2020
