### ISSUE TITLE
[launch] SEO, Security, Redirects and Analytics

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/bezos-frontend#91]
## Summary
Capturing a number of tasks that need to be confirmed or actioned as part of MVP launch of Carbonmark

## To-Do's 
Note: each of these could/should become their own issue.

- [x] Search Engine Optimization (SEO): Optimize the website for search engines by researching keywords, creating meta descriptions and titles
- [x] ~Security: Implement security measures such as SSL certificates, firewalls, and backups to protect the website from hacking and data loss~
- [x] #117
- [x] #118
- [x] ~Performance - Testing the website's load time, scalability, and response time under various conditions, such as high traffic volume, to ensure it can handle the expected traffic and perform optimally for users~
